/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5eb30f1582f82d390e78546a
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import { DateTimePicker } from "material-ui-pickers";

// Custom Actions


// START IMPORT ACTIONS
import UserProfilesActions from "../redux/actions/UserProfilesActions";

// END IMPORT ACTIONS

/** APIs

* actionsUserProfiles.create
*	@description CRUD ACTION create
*
* actionsUserProfiles.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsUserProfiles.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*

**/

class UserProfilesEdit extends Component {
  // Init userprofiles
  constructor(props) {
    super(props);
    this.state = {
      userprofiles: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsUserProfiles.loadUserProfiles(this.props.match.params.id);
    }
    
  }

  // Insert props userprofiles in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      userprofiles: props.userprofiles
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.userprofiles._id) {
      this.props.actionsUserProfiles.saveUserProfiles(this.state.userprofiles).then(data => {
        this.props.history.push("/userprofileses/");
      });
    } else {
      this.props.actionsUserProfiles.createUserProfiles(this.state.userprofiles).then(data => {
        this.props.history.push("/userprofileses/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>UserProfiles Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="CurrentCity"
            label="CurrentCity"
            value={this.state.userprofiles.CurrentCity || ""}
            onChange={Utils.handleChange.bind(this, "userprofiles")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.userprofiles.CurrentCity && this.state.userprofiles.CurrentCity === ""
              ? { error: true }
              : {})}
          />
          
          <DateTimePicker
            id="DOB"
            label="DOB"
            className="mt-20 mb-20"
            ampm={false}
            value={
              this.state.userprofiles.DOB
                ? new Date(this.state.userprofiles.DOB)
                : null
            }
            onChange={Utils.handleChangeDate.bind(this, "userprofiles", "DOB")}
            fullWidth
            autoOk
            disableFuture
            required
            {...(!this.state.userprofiles.DOB && this.state.userprofiles.DOB === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="FIrstName"
            label="FIrstName"
            value={this.state.userprofiles.FIrstName || ""}
            onChange={Utils.handleChange.bind(this, "userprofiles")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.userprofiles.FIrstName && this.state.userprofiles.FIrstName === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="Gotra"
            label="Gotra"
            value={this.state.userprofiles.Gotra || ""}
            onChange={Utils.handleChange.bind(this, "userprofiles")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="LastName"
            label="LastName"
            value={this.state.userprofiles.LastName || ""}
            onChange={Utils.handleChange.bind(this, "userprofiles")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="TimeOfBirth"
            label="TimeOfBirth"
            value={this.state.userprofiles.TimeOfBirth || ""}
            onChange={Utils.handleChange.bind(this, "userprofiles")}
            margin="normal"
            fullWidth
          />
          

          {/* Footer */}
          <div className="footer-card">
            <Link to="/userprofileses/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsUserProfiles: bindActionCreators(UserProfilesActions, dispatch),
  };
};

// Validate types
UserProfilesEdit.propTypes = { 
  actionsUserProfiles: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    userprofiles: state.UserProfilesEditReducer.userprofiles
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(UserProfilesEdit);
