/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5eb30f1582f82d390e78546a
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// CITIES
export const CREATE_CITIES_SUCCESS = "CREATE_CITIES_SUCCESS";
export const DELETE_CITIES_SUCCESS = "DELETE_CITIES_SUCCESS";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const LIST_CITIES_SUCCESS = "LIST_CITIES_SUCCESS";
export const UPDATE_CITIES_SUCCESS = "UPDATE_CITIES_SUCCESS";

// MARITALSTATUS
export const CREATE_MARITALSTATUS_SUCCESS = "CREATE_MARITALSTATUS_SUCCESS";
export const DELETE_MARITALSTATUS_SUCCESS = "DELETE_MARITALSTATUS_SUCCESS";
export const GET_MARITALSTATUS_SUCCESS = "GET_MARITALSTATUS_SUCCESS";
export const LIST_MARITALSTATUS_SUCCESS = "LIST_MARITALSTATUS_SUCCESS";
export const UPDATE_MARITALSTATUS_SUCCESS = "UPDATE_MARITALSTATUS_SUCCESS";

// STATES
export const CREATE_STATES_SUCCESS = "CREATE_STATES_SUCCESS";
export const DELETE_STATES_SUCCESS = "DELETE_STATES_SUCCESS";
export const GET_STATES_SUCCESS = "GET_STATES_SUCCESS";
export const LIST_STATES_SUCCESS = "LIST_STATES_SUCCESS";
export const UPDATE_STATES_SUCCESS = "UPDATE_STATES_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// USERPROFILES
export const CREATE_USERPROFILES_SUCCESS = "CREATE_USERPROFILES_SUCCESS";
export const DELETE_USERPROFILES_SUCCESS = "DELETE_USERPROFILES_SUCCESS";
export const GET_USERPROFILES_SUCCESS = "GET_USERPROFILES_SUCCESS";
export const LIST_USERPROFILES_SUCCESS = "LIST_USERPROFILES_SUCCESS";
export const UPDATE_USERPROFILES_SUCCESS = "UPDATE_USERPROFILES_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
